#!/bin/python3
import sys
from importer import *
from commonFunctions import *

'''--------------------+
|		VARIABLES		|
+---------------------'''
global flag, newProgram
rec=lambda: True if len(sys.argv)>1 else False
try:
	flag=sys.argv[1]
	newProgram=sys.argv[2]
except:
	flag=''
	newProgram=''

'''---------------------+
|		FUNCTIONS		|
+---------------------'''
def listCommands(detailed=True):
	if detailed:
		for i in Program.all_programs:
			print(i)
	else:
		for i in Program.all_programs:
			print("\033[34m\033[4m{}\033[0m".format(i.getName()))
	exit(0)

def usage():
	print('''
\033[33m{0}Usage:\033[0m progli [-adh] [PROGNAME]
\tOrganizer for installed programs, aliases, or just help with common commands.
\n\033[33m{0}Arguments:\033[0m
\t-a, --add\tAdds an entry to the list
\t-d, --delete\tRemoves an entry from the list
\t-h, --help\tPrints this screen
\t-l, --list\tLists all programs
\t-ld,\t\tLists all programs in detail
\n\033[33m{0}Examples:\033[0m
\tprogli
\tprogli -l
\t\t\033[2mJust prints the program names\033[0m\n
\tprogli -a newProgramName
\tprogli -d programToDelete
	'''.format((lambda x=rec(): "\033[0m" if x==False else "")()))
	exit(1)

'''-----------------+
|		MAIN		|
+-----------------'''
def main():
	global flag, newProgram
	#List all commands is no arg was given
	if len(sys.argv)==1:
		listCommands()

	#Print Program if only a name was given
	elif len(sys.argv)==2 and 0<ord(sys.argv[1][0].upper())-65<25: #Check if first char is a letters
		for i in Program.all_programs:
			if i.getName()==sys.argv[1]:
				print(i)
				exit(0)
		error("progli.main", "Program not found!")

	#Parse command line arguments
	elif len(sys.argv)==2:
		if flag in ["-h", "--help"]:
			usage()
		elif flag in ["-l", "--list"]:
			listCommands(False)
		elif flag=="-ld":
			listCommands()
		else:
			usage()

	#Prints error if more than 2 args given
	elif len(sys.argv)>3:
		error("progli.main", "Too many arguments given!")

	#Print an error if no name was given
	elif sys.argv[1][0]=='-' and not 0<ord(sys.argv[2][0].upper())-65<25:
		error("progli.main", "No program name given! Use \"progli -h\" for help")

	#Processes arguments
	if flag in ["-a", "--add"]:
		print("Add!")
		with open("./.progli/program_list.test", "a") as program_list:
			curProgram=Program(newProgram)
			description=str(input("Description (leave blank for none):\n"))

			#Write new Program to the program_list file
			program_list.write("-{}\n".format(curProgram.getName()))
			if description!='':
				program_list.write("({})\n".format(description))
			program_list.write(";\n")
		exit(0)
	elif flag in ["-d", "--delete"]:
		print("Delete!")
		exit(0)
	elif flag in ["-e", "--edit"]:
		print("Edit!")
		exit(0)

	print("End of main!")
	usage()

if __name__=="__main__":
	main()
