#!/bin/python3
## Author:	Owen Cocjin
## Version:	0.2
## Date:	30/04/19
## Description: Program to manage a custom list of installed programs

import sys, time
from menu import *
from importer import *
from common import *

'''--------------------+
|		VARIABLES		|
+---------------------'''


'''---------------------+
|		FUNCTIONS		|
+---------------------'''
def listCommands(detailed=True):
	if detailed:
		print()
		for i in Program.all_programs:
			print(i)
	else:
		for i in Program.all_programs:
			print(i.getName())
	exit(0)

'''-----------------+
|		MAIN		|
+-----------------'''
def main():
	#List all commands is no arg was given
	if len(flags)+len(args)==0:
		listCommands()

	#Print Program if only a name was given
	elif len(flags)==0 and 0<ord(args[0][0].upper())-65<25: #Check if first char is a letters
		onlyName()

	#Parse command line arguments. all the following flags don't need args
	if len(args)==0:
		print("Help args")
		[usage() for i in flags if i in ['h', "help"]]
		[listCommands((lambda :True if 'd' in flags else False)()) for i in flags if i in ['l', "list"]]

	#Print an error if no name was given to a flag that needs an arg
	if len(flags)>0 and len(args)==0:
		error("progli.main", "No program name given! Use \"progli -h\" for help")

	[add() for i in flags if i in ['a', "add"]]  #Get info and add it to program_list file

	[delete() for i in flags if i in ['d', "delete"]]  #Delete specified program

	[edit() for i in flags if i in ['e', "edit"]]  #Edit a specific program

	print("Final usage!")
	usage()

if __name__=="__main__":
	main()

#To: This program,
#Luv u!
